version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch
